// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmaZwCT7cEVSL6PpkwShUePIv5ONOCGc4',
    appId: '1:947266600451:web:97ead3a020d1e2b360d836',
    messagingSenderId: '947266600451',
    projectId: 'reminders-d5c2f',
    authDomain: 'reminders-d5c2f.firebaseapp.com',
    storageBucket: 'reminders-d5c2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhgBbT6VA5RfcLlrx6TOxUgE5oGhA8Zt4',
    appId: '1:947266600451:android:afccb9374256154360d836',
    messagingSenderId: '947266600451',
    projectId: 'reminders-d5c2f',
    storageBucket: 'reminders-d5c2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsnnlLU6WGYGH4JeU5feHDqJvwiYZazOM',
    appId: '1:947266600451:ios:9e8d56c469bda99160d836',
    messagingSenderId: '947266600451',
    projectId: 'reminders-d5c2f',
    storageBucket: 'reminders-d5c2f.appspot.com',
    iosBundleId: 'com.example.reminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsnnlLU6WGYGH4JeU5feHDqJvwiYZazOM',
    appId: '1:947266600451:ios:4f1dc596ac227b7560d836',
    messagingSenderId: '947266600451',
    projectId: 'reminders-d5c2f',
    storageBucket: 'reminders-d5c2f.appspot.com',
    iosBundleId: 'com.example.reminder.RunnerTests',
  );
}
